### ISSUE TITLE
Make TreeAssertions independent of insertion order (for FileImporter)

### ISSUE THREAD

**Issue by fgutmann** [dc2f/dstore-java#4]
There are some `System.out.println` statements left in the code (eg. FileImporter). Search for them and replace them with logging statements.

Getting a console output for all contents during a large folder import is quite annoying ;-)

**Comment by fgutmann** [comment]
Already removed the ones from FolderImporter. I also removed the main method in order to replace it by a test. Unfortunately I encountered some problems that need to be fixed before the test will run stable.

The current status of the test is available in the working branch test-folder-import.

**Comment by hpoul** [comment]
well, i tried to fix a problem, but i'm not sure if this is the problem you're referring to.. 

we can currently assume that the order of children are always preserved.. and we can assume that the file walk tree (folder importer) always traverses directories before files.. (otherwise files can't be added to directories) .. but we can't be sure of the order of which directories and files are iterated over: http://stackoverflow.com/questions/10396649/order-of-traversal-in-files-walkfiletree

imo we should just change the implementation of the TreeAssertions to be a "NameAwareTreeAssertion" implementation which simply checks by name, and does not allow same name siblings.. since the underlying implementation doesn't care about names, i think we can add that restrictions to our tests.. (maybe add an additional test to make sure SNS are working as expected)

any thoughts?

p.s. it seems the mac osx vm traverses differently than on linux, because for me 'root.json' is added AFTER the other folders.. while on linux it's the first thing to get added.. so this is no fix at all..

**Comment by fgutmann** [comment]
Yes, this was exactly the problem I encountered too and also came to the
conclusion to fix the assertTree to not rely on the insertation order of
nodes.

I was going to fix it in a more general way by checking all the properties
and the children recursively. This would be performant enough for small
expected trees and would work reliably for all cases including SNS.

When I first implemented the assertTree method it was just for the
quick-fix to rely on the insertion order but I always have been aware of
this problem.

**Comment by hpoul** [comment]
ah ok, since the assertTree would simply throw an assertion error i thought it might be easier to just fetch it by name.. anyway.. as it sounds that you want to fix it anyway (and i think you've also removed all System.out msgs), i've assigned you the issue, hope you don't mind :)
otherwise just assign it back ;)

**Comment by fgutmann** [comment]
Ok, I just finished an implementation that should do the job pretty well.

The implemented algorithm checks all children recursively. 
If all properties of all children match it is recognized as the same node.
It can deal correctly with nodes that have all identical properties but different children. (eg. SNS)

May be slow for large trees and can cause StackOverflowException on deeply nested trees.
But i think those shortcomings are no problem in real tests.

File import test now works reliably across systems.
I merged the changes with master and deleted the test-folder-import branch.
